# Site Settings
title: Python in Heliophysics Community (PyHC)
title_image: "https://github.com/heliophysicsPy/heliophysicsPy.github.io/blob/87cd99dd4833cc18fc7b10b7882c7fd93f579938/img/PyHC%20logo%20250x250.png"
description: "Promoting and facilitating the use and development of Python for Heliophysics."
url: "https://heliopython.org/"

# Social username/URLs
twitter_username: PyHC_official

# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
plugins:
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-paginate
paginate: 5
paginate_path: "/blog/page:num/"
collections:
  - pages
exclude:
  - LICENSE.md
  - README.md
