# Site Settings
title: Python in Heliophysics
description: >
  A guide to getting started with Python in Heliophysics.
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-mentions
  - jekyll-seo-tag
