# Site Settings
title: HeliophysicsPy
description: >
  A guide to getting started with Jekyll.
baseurl: "/startjekyll"
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
