# Site Settings
title: Python in HeliophysicsPy
project_title: helioPy
author:
  twitter: ehsteve
description: >
  A guide to getting started with Python in Heliophysics.
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-mentions
  - jekyll-seo-tag
