# Site Settings
title: Python in Heliophysics Community (PyHC)
description: "A website to promote and facilitate the use and development of Python for Heliophysics."
# Build Settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
gems:
  - jekyll-mentions
  - jekyll-seo-tag
collections:
  - pages
exclude:
  - LICENSE.md
  - README.md
